### ISSUE TITLE
コードの実行をサンドボックスっぽくする

### ISSUE THREAD

**Issue by Nerahikada** [NeiroNetwork/EvalBook#15]
目的: Mainから魔法(hack)を取り除く
`evaler/` らへんにFakePluginBaseみたいなのを作る

**Comment by Nerahikada** [comment]
evaler → evaluator の方がいいのでは (by @famima65536)

**Comment by famima65536** [comment]
❤️

**Comment by Nerahikada** [comment]
実はFakePluginが過去に居ました: NeiroNetwork/EvalBook@21a8e9171ccc45c50717aa020ed4dab796d0ff55

**Comment by Nerahikada** [comment]
最初に書いてあることとは違いますが、実際やりたかったことはサンドボックス化だったと思います
thanks @yuyaprgrm

**Comment by Nerahikada** [comment]
#8 とも関連: Mainが動的プロパティで汚染されるのを防げる
